### ISSUE TITLE
RuntimeError: Error when processing image.jpg

### ISSUE THREAD

**Issue by UtopianElectronics** [Philipp91/picasa2digikam#19]
Picasa has somehow made two `.picasa.ini` files in a folder. After successfully running picasa2digikam the first time, which must have used the `.picasa.ini` file, I deleted it and renamed the `.picasa (2).ini` file to `.picasa.ini` and re-run the program. The following error is displayed during the dry-run:
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\picasa2digikam\migrator.py", line 169, in migrate_directory
    migrate_file(filename, image_id, ini_section, db, album_to_tag, contact_to_tag, global_names,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\picasa2digikam\migrator.py", line 227, in migrate_file
    migrate_face(image_id, filename, face_data, db, contact_to_tag, global_names,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\picasa2digikam\migrator.py", line 297, in migrate_face
    raise RuntimeError(
RuntimeError: digiKam already has face rectangle <rect x="407" y="12" width="133" height="159"/> defined. Please specify what to do by running with argument --skip_same_rect or --no-skip_same_rect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USERNAME\picasa2digikam\main.py", line 66, in <module>
    main()
  File "C:\Users\USERNAME\picasa2digikam\main.py", line 56, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\picasa2digikam\migrator.py", line 107, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\picasa2digikam\migrator.py", line 175, in migrate_directory
    raise RuntimeError(f'Error when processing {input_dir / filename}') from e
RuntimeError: Error when processing D:\gallery\image.jpg
```

**Comment by UtopianElectronics** [comment]
I checked the file with Bad Peggy and it's not corrupted. But I noticed that the related entries in `.picasa.ini` and `.picasa (2).ini` are different.
From `.picasa.ini`:
```
[image.jpg]
star=yes
faces=rect64(828f05c1ad705275),9efcd3a62ca37f0e
backuphash=57758
```
From `.picasa (2).ini`:
```
[image.jpg]
star=yes
faces=rect64(828f05c1ad705275),ea0018a1f3344199
backuphash=19418
```

**Comment by UtopianElectronics** [comment]
This issue gets fixed by manually editing `.picasa (2).ini` and making the tags identical to the ones in `.picasa.ini`.

**Comment by Philipp91** [comment]
Yeah it will fail on images with conflicting face tags. That's intended. The first run with the one file inserts the one face into the database, and the second run with the second face attempts inserting it but finds the first conflicting face and thus aborts. You could just remove the face from the ini file manually if you want to continue migrating the rest.
