### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by benyamin39** [Philipp91/picasa2digikam#20]
Hi,

I am running python 3.10 on windows 10. Running the script in dry_run. I got the following erro

**OverflowError: Python int too large to convert to SQLite INTEGER**

Note that I got a previously a first error message  I had to enter --photos_dir="J:/My Pictures" instead of --photos_dir="J:My Pictures" for the script to recognize the folder. I mention it just in case the errors would be related.

here-below is the log of the error as well as the picasa.ini file (at the end). I am using Picasa 3

Thx for your help and also thx for the script.

C:\Users\Guest Account\picasa2digikam>python main.py --dry_run --photos_dir="J:/My Pictures" --digikam_db="c:\Users\Guest Account\OneDrive\Images\digikam4.db" --contacts="%LocalAppData%\Google\Picasa2\contacts\contacts.xml"
WARNING: Unused INI sections in J:\My Pictures\00_benjamin childhood\Picasa.ini: {'encoding'}
ERROR: Exception: Python int too large to convert to SQLite INTEGER
ERROR: Traceback (most recent call last):
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 181, in migrate_directory
    migrate_file(filename, image_id, ini_section, db, album_to_tag, contact_to_tag, global_names,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 239, in migrate_file
    migrate_face(image_id, filename, face_data, db, contact_to_tag, global_names,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 293, in migrate_face
    if db.image_has_tag(image_id, tag_id):
  File "C:\Users\Guest Account\picasa2digikam\digikam_db.py", line 185, in image_has_tag
    return self._fetchcell(
  File "C:\Users\Guest Account\picasa2digikam\digikam_db.py", line 217, in _fetchcell
    cur.execute(query, *args)
OverflowError: Python int too large to convert to SQLite INTEGER

Traceback (most recent call last):
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 181, in migrate_directory
    migrate_file(filename, image_id, ini_section, db, album_to_tag, contact_to_tag, global_names,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 239, in migrate_file
    migrate_face(image_id, filename, face_data, db, contact_to_tag, global_names,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 293, in migrate_face
    if db.image_has_tag(image_id, tag_id):
  File "C:\Users\Guest Account\picasa2digikam\digikam_db.py", line 185, in image_has_tag
    return self._fetchcell(
  File "C:\Users\Guest Account\picasa2digikam\digikam_db.py", line 217, in _fetchcell
    cur.execute(query, *args)
OverflowError: Python int too large to convert to SQLite INTEGER

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Guest Account\picasa2digikam\main.py", line 66, in <module>
    main()
  File "C:\Users\Guest Account\picasa2digikam\main.py", line 56, in main
    migrator.migrate_directories_under(input_root_dir=args.photos_dir, db=db,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 107, in migrate_directories_under
    contact_tags_per_dir[dir] = migrate_directory(dir, files, db,
  File "C:\Users\Guest Account\picasa2digikam\migrator.py", line 187, in migrate_directory
    raise RuntimeError(f'Error when processing {input_dir / filename}') from e
RuntimeError: Error when processing J:\My Pictures\00_bestpictures\P1000175.JPG

picasa.ini file
[Picasa]
name=00_benjamin childhood
date=36526.429167
P2category=Folders on Disk
[12Nov 001.jpg]
backuphash=34474
faces=rect64(1878155535c04592),80ed06fbd13e512e
[12Nov 002.jpg]
backuphash=25848
[12Nov.jpg]
backuphash=594
faces=rect64(985813b1afa22801),80ed06fbd13e512e
[benjamin 004.JPG]
backuphash=25848
[benjamin 005.JPG]
backuphash=25848
[benjamin 02.JPG]
backuphash=25848
[benjamin002.JPG]
backuphash=25848
[benjamin02.JPG]
backuphash=25848
[img1.JPG]
backuphash=25848
[img2.JPG]
backuphash=25848
[img4.JPG]
backuphash=25848
[img5.JPG]
backuphash=25848
[Contacts2]
80ed06fbd13e512e=Benjamin;;

**Comment by Philipp91** [comment]
Please let me know if this patch works: https://github.com/Philipp91/picasa2digikam/pull/21

**Comment by benyamin39** [comment]
It works and the script processed almost all the folders. It stumbled on a particular one. I will post another ticket if needed.
Thx
